#ifndef TEXT_ADVENTURES_ADVENTURE
#define TEXT_ADVENTURES_ADVENTURE

#include <stdbool.h>

enum InputOptions { // as many as MAX_OPTION_COUNT (common.h)
    ADVENTURE_INPUT_OPTION_1,
    ADVENTURE_INPUT_OPTION_2,
    ADVENTURE_INPUT_OPTION_3,
    ADVENTURE_INPUT_OPTION_4,
    ADVENTURE_INPUT_OPTION_5,
    ADVENTURE_INPUT_QUIT,
    ADVENTURE_INPUT_INVALID,
};

#define KEY_QUIT 'q'

void play_adventure(char *filename);

#endif // TEXT_ADVENTURES_ADVENTURE
